apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
              hostPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-server-config-volume
              mountPath: /etc/nginx/conf.d/server.conf
              subPath: server.conf
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
        - name: nginx-server-config-volume
          configMap:
            name: nginx-server-config
