apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-server-config
data:
  server.conf: |
    upstream flask_nodes {
      server flask-service:5000;
    }

    server {
      listen 80;
      server_name _;

      location / {
          proxy_pass http://flask-nodes/;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;
          proxy_set_header X-Forwarded-Prefix /;
      }

      location /socket.io {
          proxy_pass http://flask-nodes/socket.io;
          proxy_http_version 1.1;
          proxy_buffering off;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
      }
    }
